GEMScienceTools/oq-mbtk

- oqmbt/notebooks/sources_shallow_fault/shallow_faults.py
This adds a small change introduced while fixing conflicts
> Adding pending change

- oqmbt/tools/tr/catalogue.py
- oqmbt/tools/tr/classify.py
- oqmbt/tools/tr/set_crustal_earthquakes.py
- oqmbt/tools/tr/set_subduction_earthquakes.py
This PR fixes the case when earthquakes within the input catalogue are far from a subduction source e.g. catalogue for Central America and subduction source for the Lesser Antilles. I'm also adding a minimum support for logging.
> Fixes the case when eqks are not around a subduction source + logging

- openquake/mbt/tools/model_building/dclustering.py
- openquake/mbt/tools/model_building/plt_mfd.py
- openquake/mbt/tools/smooth.py
Updates the smoothing to account for the changes in the OQ hazardlib.
> Fixed bug + tools for plotting ruptures

- openquake/mbt/tests/tools/model_building/dcluster_test.py
- openquake/mbt/tools/model_building/dclustering.py
This PR generalises the dclustering function
> Improved dclustering functionalities

- .travis.yml
- openquake/mbt/tests/tools/tr/tr02_test.py
This PR adds a decorator to the slow test and changes the nosetest command accordingly.
> Fixing slow test

- openquake/man/model.py
- openquake/man/single/faults.py
- openquake/man/tests/single/fault_test.py
- openquake/mbt/notebooks/project/utils.py
- openquake/mbt/notebooks/sources_shallow_fault/create_fault_sources_from_geojson.py
- openquake/mbt/oqt_project.py
- openquake/mbt/tools/area.py
- openquake/mbt/tools/model.py
- openquake/mbt/tools/tr/classify.py
- openquake/mbt/tools/tr/tectonic_regionalisation.py
- openquake/sub/create_2pt5_model.py
- openquake/sub/create_inslab_nrml.py
- openquake/sub/create_multiple_cross_sections.py
- openquake/sub/cross_sections.py
- openquake/sub/misc/edge.py
- openquake/sub/misc/profile.py
- openquake/sub/plotting/plot_2pt5_model.py
- openquake/sub/plotting/plot_2pt5_model_mayavi.py
- openquake/sub/plotting/plot_multiple_cross_sections.py
- openquake/sub/plotting/plot_multiple_cross_sections_map.py
- openquake/sub/slab/inslab.py
- openquake/sub/slab/rupture.py
- openquake/sub/tests/cross_section_test.py
- openquake/sub/tests/trench_test.py
- openquake/sub/tests/utils_test.py
- openquake/sub/utils.py
- setup.py
With this PR we add a dependency from pylint and fix some error reported by the tool.
Included:
* a full pylint report  
[mbtk-lint.txt](https://github.com/GEMScienceTools/oq-mbtk/files/2274249/mbtk-lint.txt)
* the list of errors only  
[mbtk-errors-lint.txt](https://github.com/GEMScienceTools/oq-mbtk/files/2274248/mbtk-errors-lint.txt)
* a list of each type of pylint alerts ordered by their frequences.  
[mbtk-lint-rank.txt](https://github.com/GEMScienceTools/oq-mbtk/files/2274250/mbtk-lint-rank.txt)
**NOTE**:
To avoid problems with packages with the same ``openquake`` namespace already installed I mangled the mbtk base namespace to ``openquakez`` replacing all occurrencies  of ``openquake.{man,sub,mbt}`` with ``openquakez....``.
> Pylint partial refactoring

- openquake/mbt/tools/fault_modeler/README.md
- openquake/mbt/tools/fault_modeler/fault_modeling_utils.py
- openquake/mbt/tools/fault_modeler/fault_source_modeler.py
1) Using Leonard as default (in the modeller, not the utils)
2) Fixed some param mapping issues
> Various fixes

- openquake/mbt/notebooks/sources_area/compute_focal_mechanism_distribution.ipynb
- openquake/mbt/notebooks/sources_distributed_s/create_sources.ipynb
fixes error in focal mechanism plotting and changes naming convention for distributed seismicity to avoid repeats
> small fixes to mbtk

- openquake/ghm/bin/create_curves.sh
- openquake/ghm/create_homogenised_curves.py
WIth this PR we reduce the RAM consumption. The homogenisation of curves now works also on the hazard workstation!
> 20190529 ghm

- openquake/mbt/notebooks/sources_distributed_s/create_sources_no_faults.ipynb
This PR adds an improved version of the notebook used to model area sources without faults.
> 201906013 area src

- README.md
- requirements-py36-linux64.txt
- requirements-py36-macos.txt
- requirements-py36-win64.txt
> Update deps URLs and add win64

- openquake/man/tools/csv_output.py
- openquake/mbt/tests_qa/test01_test.py
This PR fixed a test broke by recent changes in OQ Engine .csv files format. I am updating the parser for ses in .csv to fix this.
> 20200114 fix tests

- openquake/mbt/tests/tools/tr/tr02_test.py
- openquake/sub/tests/slab/rupture_test_pai.py
First step for replacing nose with pytest. Part of https://github.com/GEMScienceTools/oq-mbtk/issues/144.
> Removed dependency from nose

- openquake/plt/mapping.py
> Fix converter

- bin/wkf_catalogue_declustering.py
- bin/wkf_completeness_plot_data.py
- bin/wkf_create_nrml_sources.py
- openquake/wkf/utils.py
Adds minor fixes for the catalogue component introduced while porting the use of scripts from local to the ones in the mbtk
> Minor fixes

- bin/wkf_completeness_plot_data.py
- openquake/mbt/tools/model_building/plt_mtd.py
- openquake/wkf/compute_gr_params.py
Cleaning implementation of wkf component
> 20210408 reorganizing

- openquake/cat/hmg/merge.py
- openquake/mbi/cat/__init__.py
- openquake/mbi/cat/check_duplicates.py
- openquake/mbi/cat/create_csv.py
- openquake/mbi/cat/create_figures.py
- openquake/mbi/cat/homogenise.py
- openquake/mbi/cat/merge.py
- openquake/mbi/cat/purge_earthquakes.py
> Adding mbi commands for catalogue

- bin/wkf_seismicity_add_baseline.py
- openquake/mbi/wkf/create_nrml_sources.py
- openquake/mbi/wkf/smooth_flat.py
This PR adds the possibility of creating multipoint sources rather than a long set of point sources
> Adding support for multipoint source

- openquake/sub/create_inslab_nrml.py
- openquake/sub/tests/slab/rupture_smooth_test.py
This is a PR that fixes the broken tests.
> Fixing test

- openquake/cat/isf_catalogue.py
- openquake/cat/tests/isf_catalogue_test.py
Updated handling of buffers to work with use_kms and added unit test for specifying buffers with use_km.
Fixes issue #289
> Fixing merge buffers

- openquake/smt/residuals/residual_plots.py
- openquake/smt/residuals/residual_plotter.py
> plot improvements

- openquake/aft/aftershock_probabilities.py
- openquake/aft/rupture_distances.py
- openquake/aft/tests/__init__.py
- openquake/aft/tests/test_aftershock_probabilities.py
@cossatot this PR is currently failing because of a test. Pls, take a look at it. Note that so far tests have not been executed on remote since there was a `__init__.py` file missing. Note also that when using files within tests it's always recommended to define for them relative paths to the test file.
> Adding paths relative to file - test now should run on remote

- openquake/mbi/ccl/create_sub_catalogues.py
- openquake/mbi/ccl/decluster_multiple_TR.py
- openquake/mbi/sub/plot_geometries.py
- openquake/sub/misc/edge.py
- openquake/sub/slab/rupture.py
- requirements_linux.txt
- requirements_macos_arm64.txt
- requirements_macos_x86_64.txt
- requirements_win64.txt
-moves a few files that were not yet in the mbi 
-increases the tolerance to 0.7 for creating the ruptures. this is something we need to address more systematically next
> Last touches

- openquake/wkf/distributed_seismicity.py
- only creates the buffer point source file if there are faults in that zone -> does not fail if there are no faults
> Buffer fix

- .github/workflows/test_deploy.yaml
- .github/workflows/test_win64.yaml
Closes https://github.com/GEMScienceTools/oq-mbtk/issues/374
> Removed oq dbserver start in the actions

- openquake/fnm/exporter.py
- openquake/fnm/fault_modeler.py
- openquake/fnm/tests/inversion/motagua_simple_test.py
- openquake/fnm/tests/test_fault_modeler.py
- openquake/fnm/tests/test_rupture_connections.py
Adds a new GeoJSON rupture exporter for the updated Fermi workflow
> Fermi export updates

- openquake/fnm/all_together_now.py
- openquake/fnm/fault_modeler.py
- openquake/fnm/msr.py
- openquake/fnm/rupture.py
- openquake/fnm/tests/msr_test.py
This is a small PR where I generalise the use of MSR from the OQ Engine and I clean some code
> Cleaned code, generalised MSR and fixed test

- docsrc/contents/wkf.rst
- docsrc/index.rst
This PR adds documentation for the wkf module of the mbtk and updates the index accordingly
> adding wkf documentation

- openquake/wkf/distributed_seismicity.py
There are two parts to this PR:
> WIP: fault buffer around distributed seis fixes

- setup.py
> set h3 <= 3.7.7

- openquake/mbi/ccl/classify.py
adds to https://github.com/GEMScienceTools/oq-mbtk/pull/476
> forgot to pass the lower_depth label early on; adding here

- openquake/sub/tests/create_profiles_from_slab2pt0_test.py
- pyproject.toml
- requirements-py310-linux.txt
- requirements-py311-linux.txt
- requirements-py312-linux.txt
- requirements_linux.txt
- requirements_macos_arm64.txt
- requirements_macos_x86_64.txt
- requirements_win64.txt
And removed redundant requirements
> Upgraded pyproj
