GEMScienceTools/oq-mbtk

- openquake/mbt/tools/tr/set_subduction_earthquakes.py
- openquake/mbt/tools/tr/tectonic_regionalisation.py
Adjusted so that the reclassified earthquakes are added to the existing classification of interface, instead of replacing it
add to ini file:
[interface_1a]
label = interface_1
folder = ../../data/tr02/edges1_if
lower_depth = 80.
low_mag = 7.5 (not mag_low)
upp_year = 1900. (not year_upp)
distance_buffer_above = 100.
distance_buffer_below = 0
> Reclass pre1900 shallow

- openquake/mbt/tests/tools/faults_test.py
- openquake/mbt/tests/tools/mfd_test.py
- openquake/mbt/tools/faults.py
- openquake/mbt/tools/mfd.py
When M_max doesn't fall on a bin edge, the earthquake occurrence rates predicted by the `rates_for_double_truncated_mfd` are not correct (they are typically too high, by a factor of 2-100).
This is described in more detail in #75.
This PR fixes that (mostly by rounding M_max to the next bin edge), and introduces a new unittest that loops through a vector of M_max and tests that the moment release rates stay invariant to M_max.
> Fix EvenlyDiscretizedMFD rates

- requirements-py36-linux64.txt
- requirements-py36-macos.txt
We bumped GDAL version in our wheelhouse to 2.4.1 because of Crave
> Bump GDAL requirement to 2.4.1

- openquake/mbt/notebooks/sources_shallow_fault/mfd_double_truncated_from_slip_rate_SRC.ipynb
- openquake/mbt/tests/data/tools/data_test_fault_conversion.geojson
- openquake/mbt/tests/tools/fault_modeler/test_fault_modeling_utils.py
- openquake/mbt/tools/fault_modeler/fault_modeling_utils.py
- openquake/mbt/tools/fault_modeler/fault_source_modeler.py
This PR is to add "m_max" as an attribute of a fault source in the MBTK.
Now, "m_max" is used in a correct manner in "mfd_double_truncated_from_slip_rate_SRC.ipynb".
If "m_max" is passed as an attribute of the source, it is used, otherwise is computed using the fault geometry (area + scaling relation).
A test was added to test_fault_modeling_utils.py
> added m_max as an attribute of src_fault

- openquake/ghm/create_map_from_curves.py
Fix the headers of global maps to reflect the correct IMT when they are created. Previously, all maps headers were 'PGA'
> GHM csv header

- README.md
- requirements-py36-linux64.txt
- requirements-py36-macos.txt
- requirements-py36-win64.txt
- requirements-py37-macos.txt
Since now we moved to Python 3.8 and GDAL is included in the engine we do not need requirements.txt
> Updated installation instructions

- openquake/cat/isc_homogenisor.py
Modifies magnitude conversion rules to work correctly with magnitude arrays as occurs [here](https://github.com/GEMScienceTools/oq-mbtk/blob/2a1cdc55d85cc7ef2e8891cf85929d63767d7da6/openquake/cat/catalogue_query_tools.py#L1106) in addition to for single values.
> Fix converter

- openquake/mbt/tests/tools/fault_modeler/test_fault_modeling_utils.py
- openquake/mbt/tools/fault_modeler/fault_modeling_utils.py
- replaces  get_values_from_tuple() with get_dip() in one position 
- adds option for net_slip_rates as scalar instead of array in net_slip_from_vert_slip_shortening()
- adds test for net_slip_from_vert_slip_shortening()
> Fm scalar fix and test 

- openquake/cat/tests/check_test.py
- openquake/cat/tests/merge_test.py
Using the simple file.write approach to write .toml files containing Windows pathnames results in files that are no longer valid TOML.
By using toml.load to load TOML into a Python dictionary and toml.dump(dict, file) to write dictionaries in TOML format, we ensure that files are encoded correctly.
> Handle Windows pathnames in TOML files

- openquake/ghm/create_homogenised_curves.py
Since the year mentioned in the models as a suffix has been removed from the shapefiles and mosaic.py, It was necessary to remove the same from L264 of create_homogenised_curves.py.
> minor fix to create_homogenised_curves.py

- bin/wkf_adaptive_smoothing.py
- openquake/mbt/tools/adaptive_smoothing.py
- openquake/wkf/wkf_h3_zones_cat.py
- openquake/wkf/wkf_info_gain.py
Adds Helmstetter adaptive smoothing functions to mbtk. 
* Adds a module for adaptive smoothing of catalogue data, plotting smoothing output and testing the information gain for parameter calibration
* Adds a workflow implementation to fit within the mbt_wkf example. Direct comparison with existing wkf smoothing is provided by wkf_info_gain (though this is currently slower than information gain comparisons in adaptive_smoothing directly).
> Adaptive smoothing

- openquake/smt/residuals/gmpe_residuals.py
- openquake/smt/residuals/residual_plotter.py
- openquake/smt/tests/file_samples/conf_example.toml
- openquake/smt/tests/residuals/gmpe_ranking_metrics_wrt_imt_test.py
- openquake/smt/tests/residuals/residuals_test.py
Allows use of non-ergodic gmpes and gmpes requiring additional input files within SMT through specifying additional parameters within a .toml file. An example .toml file is also provided.
> Implement toml file gmpe lists

- openquake/cat/hmg/merge.py
- openquake/cat/tests/merge_test.py
log files for merge were not being passed correctly to the merge function and so merge log files were created in a default location, except on windows where this didn't work.
Now log file can be specified under 'general' or with a specific catalogue in the .toml and should be passed correctly, and where no default is supplied the file will be stored in the location of the .toml file (which is now set up to work with windows file locations).
> fixing handling of merge log files

- openquake/ghm/grid/get_sites.py
get_sites.py was putting check.shp in a /tmp file - this doesn't work on windows. 
modified output destination for check.shp to the output folder specified in the function.
> Changing /tmp/ destinations

- setup.py
- windows/install_oqmbtk.ps1
@CB-quakemodel related to issue #383
> Use python3.11 for Powershell script installation of oq and mbtk

- openquake/smt/comparison/compare_gmpes.py
- openquake/smt/comparison/utils_compare_gmpes.py
- openquake/smt/demos/demo_comparison_analysis_inputs.toml
- openquake/smt/demos/demo_comparison_script.py
Adding datastore (in form of a dictionary) of the attenuation curves, so that the user can obtain the actual curves per gmm per mag and depth per imt with the additional params specified in the config file (e.g. vs30, number of epsilon sampled from gmm sigma), so that they can manipulate this data themselves)
> adding data store of attenuation curves

- openquake/wkf/distributed_seismicity.py
- openquake/wkf/tests/data/areas_and_faults/area_01.xml
- openquake/wkf/tests/data/areas_and_faults/fault_01.xml
- openquake/wkf/tests/distributed_seismicity_test.py
This PR expands the tool's capabilities to merge distributed seismicity sources with shallow crust faults. In a following PR, we will add support for a set of sections forming a fault system. 
Example of output from the implemented test:
> Adding support for area sources

- docsrc/contents/smt.rst
- openquake/smt/comparison/compare_gmpes.py
- openquake/smt/comparison/utils_compare_gmpes.py
- openquake/smt/demos/demo_comparison_analysis_inputs.toml
- openquake/smt/tests/comparison/comparison_test.py
- openquake/smt/tests/comparison/data/Chamoli_1999_03_28_EQ.toml
- openquake/smt/tests/comparison/data/compare_gmpe_inputs.toml
- openquake/smt/tests/comparison/data/mgmpe_inputs.toml
It was confusing before, it now explains better that it is the region used (either global or japan) to estimate basin params (z1pt0 or z2pt5) if not specified directly by the user.
> Explain the basin term in the toml better

- openquake/cat/completeness/analysis.py
- openquake/fnm/inversion/utils.py
This PR adds an argument the modified `get_completeness_counts` function in the HMTK to return empty arrays instead of breaking when there is a certain common incompatibility between a candidate completeness table and the catalog. The `_completeness_analysis` function is already set up to deal with empty arrays when a completeness table and catalog are incompatible, so now it continues without error, evaluating all the requested completeness tables.
See https://github.com/gem/oq-engine/pull/10528.
> Make completeness analysis robust to a certain common failure

- openquake/smt/response_spectrum.py
`_get_time_series` was bottlenecking my workflows using the `get_response_spectrum` function. This PR applies numba to speed up everything. Before with use of `pool.map` and `get_response_spectrum` to process the records grouped by event_id in my internal workflow it was still taking about 24 hours to process about 8000 records each with 3 components which is not practical, with this modification it takes approximately 4 hours (still slow but at least reasonable now).
Identical values are obtained in the unit tests for the response spectrum functions
> use numba for spectra calcs

- openquake/man/tools/plot_3d_disagg.py
dstore_fname was called calc_id in the actual list of params for 3d disagg plotting
> change var name to match docstring in 3d disagg plotting 
